title = "Mateusz Dymiński"
baseURL = "https://mateuszdyminski.com"
languageCode = "en-us"
theme = "gohugo-theme-ananke"
themesDir = "themes"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 
googleAnalytics = "UA-143895116-1"
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = "https://www.facebook.com/mateusz.dyminski.3"
  twitter = "https://twitter.com/m_dyminski"
  instagram = ""
  youtube = ""
  github = "https://github.com/mateuszdyminski"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/mdyminski"
  mastodon = ""
  background_color_class = "bg-black"
  recent_posts_number = 6
  disqusShortname = "mateuszdyminski"
  custom_css = ["css/custom.css"]

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About me"
    url = "/about/"
    weight = -160

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = -150
  
  [[menu.main]]
    identifier = "talks"
    name = "Talks"
    url = "/talks/"
    weight = -140

  [[menu.main]]
    identifier = "trainings"
    name = "Trainings"
    url = "/trainings/"
    weight = -130

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = -120
